### ISSUE TITLE
Download link dont work

### ISSUE THREAD

**Issue by Hofstad** [on1arf/echolink-raspi#1]
Hi
I cant download with the download link "http://download.thelinkbox.net/thelinkbox-latest.tgz" My raspberry pi get rejected. Looks like that nothing to download on with that url.

Am I doing something wrong. Use the command "wget http://download.thelinkbox.net/thelinkbox-latest.tgz"

**Comment by on1arf** [comment]
Hi,

I have forwared your remark to the "thelinkbox" mailing-list on yahoo which is the main support forum for tlb. Other people have indeed confirmed this. There is currently no reply from the author of the software; but there are some other people who offer to provide the software if needed.

More info here: https://groups.yahoo.com/neo/groups/thelinkbox/info

Cheerio!
Kr. Bonne.

**Comment by on1arf** [comment]
Hi,

According the messages on the yahoo-group, the server is back up and the file is accessable again. I will close the ticket.

73
kristoff - ON1ARF
